Add fpm to dev container image to avoid podman in docker in GitHub actions (#2012)
Summary: Add fpm to dev container image to avoid podman in docker in
GitHub actions

The production cli release build fails on these steps. The container
running the job is unable to create new namespaces and runs into the
following error:

```
+ podman run -i --rm -v /tmp/tmp.oCPtyljlYd:/src/ -v /__w/pixie/pixie:/image docker.io/cdrx/fpm-fedora:24 fpm -f -p /image/pixie-px-0.8.3.x86_64.rpm -s dir -t rpm -n pixie-px -v 0.8.3 --prefix /usr/local/bin px
time="2024-09-06T18:10:15Z" level=warning msg="\"/\" is not a shared mount, this could cause issues or missing mounts with rootless containers"
cannot clone: Operation not permitted
Error: cannot re-exec process
```

Rather than fix the namespace creation problem, which has been difficult
to debug, this installs the necessary tools within the container. This
will allow us to avoid using podman to run `fpm`.

This change also reverts the previous attempt at fixing this and removes
genny from the container image. See [this
comment](https://github.com/pixie-io/pixie/pull/2012#discussion_r1751309786)
for more details on the genny removal.

Relevant Issues: #1993

Type of change: /kind bugfix

Test Plan: Verified that building the deb and rpm packages works from
the ubuntu based dev container image and that installing the packages is
successful in their respective distros
```
$ docker run --entrypoint bash -it docker.io/ddelnano/dev_image:202409082304
root@f65d4d86e9be:/src# fpm -f -s dir -t rpm -n pixie-px -v 0.8.3 --prefix /usr/local/bin  -p pixie-px-0.8.3.x86_64.rpm px
Created package {:path=>"pixie-px-0.8.3.x86_64.rpm"}
root@f65d4d86e9be:/src# fpm -f -s dir -t deb -n pixie-px -v 0.8.3 --prefix /usr/local/bin  -p pixie-px-0.8.3.deb  px
Created package {:path=>"pixie-px-0.8.3.deb"}

# Install the rpm package and test px in a fedora container
$ docker run --entrypoint bash -it -v $(pwd):/src/ -w /src fedora
[root@90a53608bae0 src]# rpm -i pixie-px-0.8.3.x86_64.rpm
[root@90a53608bae0 src]# px --version
Pixie CLI
```
- Verified chef works against a Ubuntu noble VM
- [ ] Ran `#ci:ignore-deps` and `#ci:bpf-build-all-kernels` build due to
genny removal

---------

Signed-off-by: Dom Del Nano <ddelnano@gmail.com>
GitOrigin-RevId: 07fff004cbf4cdb43910daa5e9b93da293dbf690