Increase ASAN short test timeout to address flaky tests (#2294)
Summary: Increase ASAN short test timeout to address flaky tests

The following tests are frequently hitting the 2-minute Bazel timeout on
ASAN builds:
- `//src/vizier/services/agent/shared/manager:heartbeat_test`
- `//src/vizier/services/agent/shared/manager:registration_test`
- `//src/carnot/builtins:collections_test`

BuildBuddy history from the main branch shows these tests are running up
against the timeout threshold (see screenshot below). I believe
BuildBuddy is under reporting the issues seen since builds are also
seeing BEP API timeouts.

<img width="912" height="512" alt="Screenshot 2025-12-10 at 12 05 55 PM"
src="https://github.com/user-attachments/assets/3a7632b9-ef1d-407b-81aa-1f9babdbaea3"
/>

```
//src/vizier/services/agent/shared/manager:heartbeat_test               TIMEOUT in 120.5s
  /github/home/.cache/bazel/_bazel_root/56ec069a32c4abebc78228236a835895/execroot/px/bazel-out/k8-dbg/testlogs/src/vizier/services/agent/shared/manager/heartbeat_test/test.log
//src/vizier/services/agent/shared/manager:registration_test            TIMEOUT in 120.5s
  /github/home/.cache/bazel/_bazel_root/56ec069a32c4abebc78228236a835895/execroot/px/bazel-out/k8-dbg/testlogs/src/vizier/services/agent/shared/manager/registration_test/test.log

[ ... ]
ERROR: The Build Event Protocol upload timed out. com.google.common.util.concurrent.TimeoutFuture$TimeoutFutureException: Timed out: NonCancellationPropagatingFuture@6ce6bba6[status=PENDING, info=[delegate=[SettableFuture@29e4285e[status=PENDING]]]]
Bazel returned code 38, ignoring...
```

This PR increases the short test timeout to unblock ongoing Bazel 7
upgrade work and prevent unrelated PRs from failing due to these
timeouts.

Relevant Issues: #2295

Type of change: /kind bugfix

Test Plan: Build succeeds

---------

Signed-off-by: Dom Del Nano <ddelnano@gmail.com>
GitOrigin-RevId: f4e30ef78c991fbf8e59615c843c0e0fcfdb219d